# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a415fd7eeb8a748340af8ae10764b67f3ce8415c4238539f32dba5f20737f53622c45580b5e56800bca02114e589da57b78dadfb89f675aff1973e82409694

test:
  secret_key_base: c0415edefde3b9aaaaedb37ad7c414ff47724a237793d61d0b486f5beffff343a1ce81f8073e957be0ace9603cf5990b39b29a676256d8874bb887f9f3eea285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
